### ISSUE TITLE
Parsed JavadocComment misses closing slash

### ISSUE THREAD

**Issue by kossmoboleat** [rpau/walkmod-javalang-plugin#3]
When deleting the JavaDoc on a class most of the comment is deleted except the closing slash "/".
I'm guessing the token misses one column when parsing, but I'm unable to understand the ASTParser.

Groovy script:
for(type in node.types){  
    type.setJavaDoc(null);
}

input:
package org.walkmod.quickstart.model;

/**
- This class is awesome
  **/
  public class Tweet {}

output:
package org.walkmod.quickstart.model;

/
public class Tweet {}

**Comment by rpau** [comment]
Thanks for reporting this. I will take a look

**Comment by rpau** [comment]
Fixed. If you run again Walkmod, you will get the fix automatically
